environment/sample_app/config/routes.rb
Rails.application.routes.draw do
  get 'todolists/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'top' => 'homes#top'
  post 'todolists' => 'todolists#create'
  get 'todolists' => 'todolists#index'
  # .../todolists/1や.../todolists_3に該当する
  get 'todolists/:id' => 'todolists#show',as: 'todolist'
  get 'todolists/:id/edit' => 'todolists#edit', as: 'edit_todolist'
  patch 'todolists/:id' => 'todolists#update', as: 'update_todolist'
  delete 'todolists/:id' => 'todolists#destroy', as: 'destroy_todolist'
end

environment/sample_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

environment/sample_app/app/models/list.rb
class List < ApplicationRecord
  # modelsにアタッチメント追加
  attachment :image

  # バリデーション　presence(存在)trueで必須
  validates :title, presence: true
  validates :body, presence: true
  validates :image, presence: true

end

environment/sample_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

environment/sample_app/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end 
  
end

environment/sample_app/app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  def new
    @list = List.new
  end

  def create
    #旧 #1.データを新規登録するためのインスタンス作成
    # 旧list = List.new (list_params)
    #旧 #2.データをデータベースに保存するためのsaveメソッド実行
    #旧 list.save
    #旧 #3.詳細画面へリダイレクト
    #旧redirect_to todolist_path(list.id)
     # 更新。返されたバリデーションの結果をコントローラで検証できるように
    @list =List.new(list_params)
    if @list.save
      redirect_to todolist_path(@list.id)
    else
      render :new
    end
  end

  # 一覧表示であり複数あるため（lists)、全て取得する（all)
  def index
    @lists = List.all
  end

  # 詳細画面
  def show
    @list = List.find (params[:id])
  end

  # データ編集画面
  def edit
    @list = List.find(params[:id])
  end

  # 編集できるようにする
  def update
    list = List.find(params[:id])
    list.update(list_params)
    redirect_to todolist_path(list.id)
  end

  def destroy
    list =List.find(params[:id])
    list.destroy  #データ（レコード）を削除
    redirect_to todolists_path
  end

  private
  #ストロングパラメータ
  def list_params
    params.require(:list).permit(:title,:body,:image)
  end

end

environment/sample_app/app/helpers/application_helper.rb
module ApplicationHelper
end

environment/sample_app/app/helpers/homes_helper.rb
module HomesHelper
end

environment/sample_app/app/helpers/todolists_helper.rb
module TodolistsHelper
end

environment/sample_app/app/views/homes/top.html.erb
<h1>ここはTopページです</h1>

environment/sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

environment/sample_app/app/views/todolists/edit.html.erb
<h1>編集画面</h1>
<%= form_with model:@list,url:"/todolists/#{@list.id}",local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <%= f.submit '保存'%>
<% end %>

environment/sample_app/app/views/todolists/index.html.erb
<!--投稿一覧-->
<h1>投稿一覧</h1>
<% @lists.each do |list| %>
    <p>タイトル</p>
    <span><%= link_to list.title, todolists_path(list.id) %></span>
    <p>画像</p>
    <%= attachment_image_tag list,:image,format: 'jpeg',size: "100x100" %>
<% end %>

environment/sample_app/app/views/todolists/new.html.erb
<h1>新規投稿</h1>
<% if @list.errors.any? %>
  <%= @list.errors.count %>件のエラーが発生しました
  <%= @list.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<!--from_with部分-->
<%= form_with model: @list,url:'/todolists',local:true do |f| %>
  <h4>タイトル</h4>
  <%= f.text_field :title %>
  <h4>本文</h4>
  <%= f.text_area :body %>
  <!--投稿用フォームに画像投稿フォーム追加-->
  <h4>画像</h4>
  <%= f.attachment_field :image %>

  <%= f.submit '投稿' %>
<% end %>

environment/sample_app/app/views/todolists/show.html.erb
<!--詳細画面-->
<h2>タイトル</h2>
<p><%= @list.title %></p>
<h2>本文</h2>
<p><%= @list.body %></p>
<h2>画像</h2>
<%= attachment_image_tag @list,:image,format:'jpeg',size: "300x300"  %>
<!--詳細画面に編集画面へのリンク設定-->
<%= link_to "編集",edit_todolist_path(@list.id) %>
<%= link_to "削除",destroy_todolist_path(@list.id),method: :delete,"data-confirm" => "本当に削除しますか？" %>